"""Minimal admin auth: verify the argon2 password hash, issue a signed session cookie.

Single-admin gate, not a user system (blueprint §18). The plaintext password is never
stored — only the argon2 hash in `ADMIN_PASSWORD_HASH`, generated by
`scripts/init_secrets.py`. The cookie is signed (not encrypted) with `SESSION_SECRET`.
"""

from __future__ import annotations

from argon2 import PasswordHasher
from argon2.exceptions import Argon2Error, VerifyMismatchError
from fastapi import HTTPException, Request, Response, status
from itsdangerous import BadSignature, SignatureExpired, URLSafeTimedSerializer
from shared import settings

COOKIE_NAME = "vrag_session"
_MAX_AGE = 60 * 60 * 8  # 8 hours

_ph = PasswordHasher()


def _serializer() -> URLSafeTimedSerializer:
    secret = settings.session_secret or "dev-only-insecure-secret"
    return URLSafeTimedSerializer(secret, salt="admin-session")


def verify_password(password: str) -> bool:
    if not settings.admin_password_hash:
        return False
    try:
        return _ph.verify(settings.admin_password_hash, password)
    except (VerifyMismatchError, Argon2Error):
        return False


def issue_session(response: Response) -> None:
    token = _serializer().dumps({"role": "admin"})
    response.set_cookie(
        COOKIE_NAME,
        token,
        max_age=_MAX_AGE,
        httponly=True,
        samesite="lax",
        secure=False,  # set True behind HTTPS in the deployment phase
        path="/",
    )


def clear_session(response: Response) -> None:
    response.delete_cookie(COOKIE_NAME, path="/")


def is_authenticated(request: Request) -> bool:
    token = request.cookies.get(COOKIE_NAME)
    if not token:
        return False
    try:
        _serializer().loads(token, max_age=_MAX_AGE)
        return True
    except (BadSignature, SignatureExpired):
        return False


def require_admin(request: Request) -> None:
    if not is_authenticated(request):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Admin login required")
